# Site settings
title: "Joon: Roon for Jekyll"
logo: logo.png # image from https://www.flickr.com/photos/lwr/5496279831/in/set-72157594159055823
email: tkteal@datacarpentry.org
description: > # this means to ignore newlines until "baseurl:"
tkt 
baseurl: "/" # the subpath of your site, e.g. /blog/
twitter_username: tracykteal
github_username:  tracykteal

# Build settings
markdown: kramdown
